version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '8181:8181'
      - '8443:8443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
